// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.3
// source: model/api/api.proto

package api

import (
	segment "a1in-bot-v3/model/segment"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action string            `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Params *APIRequestParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Echo   string            `protobuf:"bytes,3,opt,name=echo,proto3" json:"echo,omitempty"`
}

func (x *APIRequest) Reset() {
	*x = APIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest) ProtoMessage() {}

func (x *APIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest.ProtoReflect.Descriptor instead.
func (*APIRequest) Descriptor() ([]byte, []int) {
	return file_model_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *APIRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *APIRequest) GetParams() *APIRequestParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *APIRequest) GetEcho() string {
	if x != nil {
		return x.Echo
	}
	return ""
}

type APIRequestParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64              `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId    int64              `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Message    []*segment.Segment `protobuf:"bytes,3,rep,name=message,proto3" json:"message,omitempty"`
	AutoEscape bool               `protobuf:"varint,4,opt,name=auto_escape,json=autoEscape,proto3" json:"auto_escape,omitempty"`
	File       string             `protobuf:"bytes,5,opt,name=file,proto3" json:"file,omitempty"`
	Name       string             `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Folder     string             `protobuf:"bytes,7,opt,name=folder,proto3" json:"folder,omitempty"`
}

func (x *APIRequestParams) Reset() {
	*x = APIRequestParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequestParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequestParams) ProtoMessage() {}

func (x *APIRequestParams) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequestParams.ProtoReflect.Descriptor instead.
func (*APIRequestParams) Descriptor() ([]byte, []int) {
	return file_model_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *APIRequestParams) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *APIRequestParams) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *APIRequestParams) GetMessage() []*segment.Segment {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *APIRequestParams) GetAutoEscape() bool {
	if x != nil {
		return x.AutoEscape
	}
	return false
}

func (x *APIRequestParams) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *APIRequestParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIRequestParams) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type APIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  string           `protobuf:"bytes,996,opt,name=status,proto3" json:"status,omitempty"`
	Retcode int64            `protobuf:"varint,997,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Data    *APIResponseData `protobuf:"bytes,998,opt,name=data,proto3" json:"data,omitempty"`
	Echo    string           `protobuf:"bytes,999,opt,name=echo,proto3" json:"echo,omitempty"`
}

func (x *APIResponse) Reset() {
	*x = APIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse) ProtoMessage() {}

func (x *APIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse.ProtoReflect.Descriptor instead.
func (*APIResponse) Descriptor() ([]byte, []int) {
	return file_model_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *APIResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *APIResponse) GetRetcode() int64 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *APIResponse) GetData() *APIResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *APIResponse) GetEcho() string {
	if x != nil {
		return x.Echo
	}
	return ""
}

type APIResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIResponseData) Reset() {
	*x = APIResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponseData) ProtoMessage() {}

func (x *APIResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponseData.ProtoReflect.Descriptor instead.
func (*APIResponseData) Descriptor() ([]byte, []int) {
	return file_model_api_api_proto_rawDescGZIP(), []int{3}
}

var File_model_api_api_proto protoreflect.FileDescriptor

var file_model_api_api_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x1b, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x0a, 0x41, 0x50, 0x49,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2f, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x65, 0x63, 0x68, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x65, 0x63, 0x68, 0x6f, 0x22, 0xd1, 0x01, 0x0a, 0x10, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x28, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x6f, 0x5f,
	0x65, 0x73, 0x63, 0x61, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x75,
	0x74, 0x6f, 0x45, 0x73, 0x63, 0x61, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x22, 0x83, 0x01, 0x0a, 0x0b, 0x41, 0x50, 0x49,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0xe4, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x19, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xe5, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0xe6, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x13, 0x0a, 0x04, 0x65, 0x63, 0x68,
	0x6f, 0x18, 0xe7, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x63, 0x68, 0x6f, 0x22, 0x11,
	0x0a, 0x0f, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x17, 0x5a, 0x15, 0x61, 0x31, 0x69, 0x6e, 0x2d, 0x62, 0x6f, 0x74, 0x2d, 0x76, 0x33,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_model_api_api_proto_rawDescOnce sync.Once
	file_model_api_api_proto_rawDescData = file_model_api_api_proto_rawDesc
)

func file_model_api_api_proto_rawDescGZIP() []byte {
	file_model_api_api_proto_rawDescOnce.Do(func() {
		file_model_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_api_api_proto_rawDescData)
	})
	return file_model_api_api_proto_rawDescData
}

var file_model_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_model_api_api_proto_goTypes = []interface{}{
	(*APIRequest)(nil),       // 0: model.APIRequest
	(*APIRequestParams)(nil), // 1: model.APIRequestParams
	(*APIResponse)(nil),      // 2: model.APIResponse
	(*APIResponseData)(nil),  // 3: model.APIResponseData
	(*segment.Segment)(nil),  // 4: model.Segment
}
var file_model_api_api_proto_depIdxs = []int32{
	1, // 0: model.APIRequest.params:type_name -> model.APIRequestParams
	4, // 1: model.APIRequestParams.message:type_name -> model.Segment
	3, // 2: model.APIResponse.data:type_name -> model.APIResponseData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_api_api_proto_init() }
func file_model_api_api_proto_init() {
	if File_model_api_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_api_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequestParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_api_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_api_api_proto_goTypes,
		DependencyIndexes: file_model_api_api_proto_depIdxs,
		MessageInfos:      file_model_api_api_proto_msgTypes,
	}.Build()
	File_model_api_api_proto = out.File
	file_model_api_api_proto_rawDesc = nil
	file_model_api_api_proto_goTypes = nil
	file_model_api_api_proto_depIdxs = nil
}
