// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.6.1
// source: model/segment/segment.proto

package segment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Segment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 消息类型
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// 负载数据
	Data *Segment_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Segment) Reset() {
	*x = Segment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_segment_segment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_model_segment_segment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_model_segment_segment_proto_rawDescGZIP(), []int{0}
}

func (x *Segment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Segment) GetData() *Segment_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Segment_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 纯文本内容，type == text
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// QQ 表情 ID，type == face
	// 回复时引用的消息 ID，type == reply
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// 图片文件名，type == image，支持绝对路径、网络 URL、Base64 编码
	// 语音文件名，type == record，支持绝对路径、网络 URL、Base64 编码
	// 视频文件名，type == video，支持绝对路径、网络 URL、Base64 编码
	File string `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	// 图片类型，flash 表示闪照，无此参数表示普通图片，type == image
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// 图片 URL，type == image
	// 语音 URL，type == record
	// 视频 URL，type == video
	// 链接分享 URL，type == share
	Url string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	// 只在通过网络 URL 发送时有效，表示是否使用已缓存的文件，默认 1
	Cache string `protobuf:"bytes,6,opt,name=cache,proto3" json:"cache,omitempty"`
	// 只在通过网络 URL 发送时有效，表示是否通过代理下载文件，默认 1
	Proxy string `protobuf:"bytes,7,opt,name=proxy,proto3" json:"proxy,omitempty"`
	// 只在通过网络 URL
	// 发送时有效，单位秒，表示下载网络文件的超时时间，默认不超时
	Timeout string `protobuf:"bytes,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// @的 QQ 号，all 表示全体成员，type == at
	Qq string `protobuf:"bytes,9,opt,name=qq,proto3" json:"qq,omitempty"`
	// 链接分享标题，type == share
	Title string `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *Segment_Data) Reset() {
	*x = Segment_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_segment_segment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Segment_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment_Data) ProtoMessage() {}

func (x *Segment_Data) ProtoReflect() protoreflect.Message {
	mi := &file_model_segment_segment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment_Data.ProtoReflect.Descriptor instead.
func (*Segment_Data) Descriptor() ([]byte, []int) {
	return file_model_segment_segment_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Segment_Data) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Segment_Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Segment_Data) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Segment_Data) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Segment_Data) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Segment_Data) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *Segment_Data) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *Segment_Data) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *Segment_Data) GetQq() string {
	if x != nil {
		return x.Qq
	}
	return ""
}

func (x *Segment_Data) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_model_segment_segment_proto protoreflect.FileDescriptor

var file_model_segment_segment_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2f,
	0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x22, 0x99, 0x02, 0x0a, 0x07, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xd0, 0x01,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x71, 0x71,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x71, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x42, 0x1b, 0x5a, 0x19, 0x61, 0x31, 0x69, 0x6e, 0x2d, 0x62, 0x6f, 0x74, 0x2d, 0x76, 0x33, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_segment_segment_proto_rawDescOnce sync.Once
	file_model_segment_segment_proto_rawDescData = file_model_segment_segment_proto_rawDesc
)

func file_model_segment_segment_proto_rawDescGZIP() []byte {
	file_model_segment_segment_proto_rawDescOnce.Do(func() {
		file_model_segment_segment_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_segment_segment_proto_rawDescData)
	})
	return file_model_segment_segment_proto_rawDescData
}

var file_model_segment_segment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_segment_segment_proto_goTypes = []interface{}{
	(*Segment)(nil),      // 0: model.Segment
	(*Segment_Data)(nil), // 1: model.Segment.Data
}
var file_model_segment_segment_proto_depIdxs = []int32{
	1, // 0: model.Segment.data:type_name -> model.Segment.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_segment_segment_proto_init() }
func file_model_segment_segment_proto_init() {
	if File_model_segment_segment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_segment_segment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Segment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_segment_segment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Segment_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_segment_segment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_segment_segment_proto_goTypes,
		DependencyIndexes: file_model_segment_segment_proto_depIdxs,
		MessageInfos:      file_model_segment_segment_proto_msgTypes,
	}.Build()
	File_model_segment_segment_proto = out.File
	file_model_segment_segment_proto_rawDesc = nil
	file_model_segment_segment_proto_goTypes = nil
	file_model_segment_segment_proto_depIdxs = nil
}
